version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: certificados_app
    restart: always
    ports:
      - "8000:8000"
      
  nginx:
    image: nginx:latest
    container_name: certificados_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app